initial attempt for light group support
rxwen/homeassistant-terncy-component pull request #19
Opened 2022-10-30 14:50 UTC by hzxa21

Initial attempt for light group support:
- Add profile for light group and hue group
- Extract neccessary information in the "devicegroup" respoonse
- Construct the TerncyLight object for light group and hue group

I haven't tested with a real device group because I don't have time to mess up with my home devices and I don't have test devices. Maybe I will try next weekend.

## Future work:
- Set the availibility of the light group acoording to the light availibility
- Error handling in `async_turn_on` and `async_turn_off`

## Help wanted for the terncy team:
- Pass the group name back in the devicegroup response
- Pass the online state back in the devicegroup response

2022-10-30 14:51 UTC, hzxa21 commented
@rxwen This is a draft PR for light group support. Feel free to take a look.

2022-10-31 15:13 UTC, rxwen requested changes

2022-11-02 14:18 UTC, hzxa21 commented on terncy/const.py
> +PROFILE_HUE_GROUP = 12
fixed

2022-11-04 12:59 UTC, rxwen commented
Thanks. LGTM.

2022-11-04 13:01 UTC, rxwen commented
There is still a conflict in terncy/__init__.py. @hzxa21

2022-11-04 16:34 UTC, hzxa21 commented
> There is still a conflict in terncy/**init**.py. @hzxa21

Fixed.

I have several help wanted from your or terncy's side:
1. I still haven't get a chance to actually test it with a terncy gateway. Any chance you can help with that? In general, if we want to make this project easier to test, we can provide some kind of mock terncy server but this may leak terncy's API and protocols. Not sure whether this is suitable.
2. However, I do test it with homeassistent (with terncy being offline) and I found out one potential issue: switching on/off for a light-group always succeeds with this PR because we use async turn on/off and terncy doesn't give back the online flag for light-group responses (I also mention this in my PR description)/. Can terncy improves this?
3. light group name is also missing in the light-group response, which annoys me a bit because I need to manual rename the light group in homeassistant. Can terncy also improves this?

2022-11-05 07:16 UTC, rxwen commented
> > There is still a conflict in terncy/**init**.py. @hzxa21
> 
> Fixed.
> 
> I have several help wanted from your or terncy's side:
> 
>     1. I still haven't get a chance to actually test it with a terncy gateway. Any chance you can help with that? In general, if we want to make this project easier to test, we can provide some kind of mock terncy server but this may leak terncy's API and protocols. Not sure whether this is suitable.

It's definitely helpful if the terncy system can be mocked for testing. To keep the API not leaked, an additional device management layer may need to be added so that the underlying communication details won't be required for testing. I'll consider about it.
And you don't have a Terncy home center right now?
> 
>     2. However, I do test it with homeassistent (with terncy being offline) and I found out one potential issue: switching on/off for a light-group always succeeds with this PR because we use async turn on/off and terncy doesn't give back the online flag for light-group responses (I also mention this in my PR description)/. Can terncy improves this?

As far as I know, a group doesn't have online flag. A group is a collection of devices that can be controlled as a whole. It is always online.
> 
>     3. light group name is also missing in the light-group response, which annoys me a bit because I need to manual rename the light group in homeassistant. Can terncy also improves this?

I think the Home Center can improve this in the coming version.

2022-11-05 08:51 UTC, hzxa21 commented
> > > There is still a conflict in terncy/**init**.py. @hzxa21
> > 
> > Fixed.
> > 
> > I have several help wanted from your or terncy's side:
> > 
> >     1. I still haven't get a chance to actually test it with a terncy gateway. Any chance you can help with that? In general, if we want to make this project easier to test, we can provide some kind of mock terncy server but this may leak terncy's API and protocols. Not sure whether this is suitable.
> 
> It's definitely helpful if the terncy system can be mocked for testing. To keep the API not leaked, an additional device management layer may need to be added so that the underlying communication details won't be required for testing. I'll consider about it.
> And you don't have a Terncy home center right now?
> > 
> >     2. However, I do test it with homeassistent (with terncy being offline) and I found out one potential issue: switching on/off for a light-group always succeeds with this PR because we use async turn on/off and terncy doesn't give back the online flag for light-group responses (I also mention this in my PR description)/. Can terncy improves this?
> 
> As far as I know, a group doesn't have online flag. A group is a collection of devices that can be controlled as a whole. It is always online.
> > 
> >     3. light group name is also missing in the light-group response, which annoys me a bit because I need to manual rename the light group in homeassistant. Can terncy also improves this?
> 
> I think the Home Center can improve this in the coming version.
> 

1. I have a home center in my new house but due to the covid situation in my city (guangzhou) i cannot go and get it... do you have a test home center that can be sent to me?

2. then even though my light goes offline, i can still set it on successfully on homeassitant. this sounds a bit counter-intuitive to me.

3. Thanks a lot!

2022-11-08 01:24 UTC, merged